namespace IndxTradeFramework.TradeApi
{   
    public enum Instrument
    {
        BTC = 60,
        LTC = 69,
        BCH = 66,
        XRP = 70,
        DASH = 71,
        XMR = 68,
        BTG = 67,
        WME = 62,
        WMR = 63,
        GOOG = 47,
        GAZP = 33,
        APPL = 48,
        QIWI = 61,
        IBM = 49,
        YNDX = 58,
        ETH = 64,
        ADBE = 53,
        AMZN = 55,
        CSCO = 50,
        FB = 59,
        FEES = 43,
        GMKn = 31,
        HYDR = 44,
        INTC = 51,
        LKOH = 35,
        MAIL = 57,
        MSFT = 46,
        MSNG = 32,
        MTS = 29,
        OGKE = 40,
        ORCL = 54,
        SNGS = 34,
        SYMC = 56,
        TATN = 37,
        VRAO = 42,
        YAHOO = 38
    }
}